name: Documentation issue
description: Report missing or incorrect documentation
title: "[DOCS] "
labels: ["documentation"]

body:
  - type: textarea
    id: issue
    attributes:
      label: What’s wrong?
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Where is the issue?

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
