name: Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        💡 You can also ask in Discord:
        https://rb.ash1421.com/discord
