name: Automated Release

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Automated File Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Skip dev/testing commits
        if: contains(steps.commit.outputs.commit_msg, 'Testing') || contains(steps.commit.outputs.commit_msg, 'Dev') || contains(steps.commit.outputs.commit_msg, 'Development')
        run: |
          echo "Commit is for Testing/Dev/Development. Skipping release."
          exit 0

      - name: Extract version
        id: version
        run: |
          VERSION=$(echo '${{ steps.commit.outputs.commit_msg }}' | grep -o 'V[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check version
        run: |
          if [ -z "${{ steps.version.outputs.VERSION }}" ]; then
            echo "No version found in commit message. Exiting."
            exit 0
          fi

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.VERSION }}
          name: Midnight-Ash Theme
          body: |
            ## Complete Discord theme pack combining Midnight-AMOLED backgrounds with Settings Modal, Radial Status, Horizontal Server List, and Apple Emojis.

            ## ✨ Socials & Stars
            [![Discord Server Invite](https://img.shields.io/badge/Discord-Server%20Invite-7289DA?style=for-the-badge&logo=discord&logoColor=white&labelColor=1c1917&color=blueviolet)](https://rb.ash1421.com/discord)
            [![GitHub Stars](https://img.shields.io/github/stars/Ash1421/Midnight-Ash?style=for-the-badge&logo=github&logoColor=white&labelColor=1c1917&color=gold)](https://github.com/Ash1421/Midnight-Ash/stargazers)

            ## Github Repository Infomation
            [![Version ${{ steps.version.outputs.VERSION }}](https://img.shields.io/badge/Version-${{ steps.version.outputs.VERSION }}-6829B1?style=for-the-badge&label=Version&logo=github&logoColor=white&labelColor=1c1917)](https://github.com/Ash1421/Midnight-Ash/releases/tag/${{ steps.version.outputs.VERSION }})
            [![Latest Version](https://img.shields.io/github/v/release/Ash1421/Midnight-Ash?style=for-the-badge&label=Latest%20Version&logo=github&logoColor=white&labelColor=1c1917&color=6829B1)](https://github.com/Ash1421/Midnight-Ash/releases/latest)
            [![CodeFactor Grade](https://img.shields.io/codefactor/grade/github/ash1421/midnight-ash?style=for-the-badge&logo=codefactor&logoColor=white&labelColor=1c1917&color=6829B1)](https://www.codefactor.io/repository/github/ash1421/midnight-ash)
            [![Total Downloads](https://img.shields.io/github/downloads/Ash1421/Midnight-Ash/total?style=for-the-badge&logo=github&logoColor=white&labelColor=1c1917&color=6829B1&label=Total%20Downloads)](https://github.com/Ash1421/Midnight-Ash/releases)
            [![Downloads at latest](https://img.shields.io/github/downloads/Ash1421/Midnight-Ash/latest/total?style=for-the-badge&logo=github&logoColor=white&labelColor=1c1917&color=6829B1&label=Downloads%20@%20latest)](https://github.com/Ash1421/Midnight-Ash/releases/latest)
            [![GitHub Issues](https://img.shields.io/github/issues/Ash1421/Midnight-Ash/open?style=for-the-badge&labelColor=1c1917&logo=github&logoColor=white)](https://github.com/Ash1421/Midnight-Ash/issues)
            [![Closed Issues](https://img.shields.io/github/issues-closed/Ash1421/Midnight-Ash/closed?style=for-the-badge&color=red&labelColor=1c1917&logo=github&logoColor=white)](https://github.com/Ash1421/Midnight-Ash/issues?q=is:closed)
            [![New Issue](https://img.shields.io/badge/Open%20A%20New-Issue-orange?style=for-the-badge&labelColor=1c1917&logo=github&logoColor=white)](https://github.com/Ash1421/Midnight-Ash/issues/new)

            ## 📜 Licensed Under
            [![License: GPL v3.0](https://img.shields.io/badge/License-GPL%20v3.0-6829B1.svg?style=for-the-badge&labelColor=1c1917&logo=gnu&logoColor=white)](./LICENSE)

            ---
            🧾 [Information About This Theme](https://github.com/Ash1421/Midnight-Ash#-infomation-about-this-theme)
            📸 [Screenshots of the theme in action](https://github.com/Ash1421/Midnight-Ash?tab=readme-ov-file#-screenshots-of-the-theme-in-action)

            👋 [Help Guide](https://github.com/Ash1421/Midnight-Ash?tab=readme-ov-file#-help-guide)
            🔓 [Editing The Theme Yourself](https://github.com/Ash1421/Midnight-Ash?tab=readme-ov-file#-editing-the-theme-yourself-%EF%B8%8F)

            📖 [Changelog](https://github.com/Ash1421/Midnight-Ash?tab=readme-ov-file#-changelog)
            📜 [License Infomation](https://github.com/Ash1421/Midnight-Ash?tab=readme-ov-file#-license-1)

            🔗 Installation URL: ```https://theme.ash1421.com/midnight-ash.css```

            Compatible with Equicord, Vencord, BetterDiscord, Replugged, and other Discord clients.

          artifacts: midnight-ash.css
