name: Publish CSS Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Auto CSS Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Skip dev/testing commits
        if: contains(steps.commit.outputs.commit_msg, 'Testing') || contains(steps.commit.outputs.commit_msg, 'Dev') || contains(steps.commit.outputs.commit_msg, 'Development')
        run: |
          echo "Commit is for Testing/Dev/Development. Skipping release."
          exit 0

      - name: Extract version
        id: version
        run: |
          VERSION=$(echo '${{ steps.commit.outputs.commit_msg }}' | grep -o 'V[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check version
        run: |
          if [ -z "${{ steps.version.outputs.VERSION }}" ]; then
            echo "No version found in commit message. Exiting."
            exit 0
          fi

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.VERSION }}
          name: Midnight-Ash Theme
          bodyFile: ./message/release-body.md
          assets: ./midnight-ash.css
